version: '3.8'

services:
  docker-counter:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
    container_name: docker-counter-local 